version: "3.9"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    networks:
      - traefiknet
    environment:
      - TZ=Europe/London
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

networks:
  traefiknet:
    external: true
