---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
{% for user in authelia.users %}
  {{ user.username }}:
    displayname: {{ user.displayname }}
    password: {{ user.password }}
    email: {{ user.email }}
    groups:
{% for group in user.groups %}
      - {{ group }}
{% endfor %}
{% endfor %}
...