version: "3.9"
services:
  basic-auth-example:
    image: nginx
    container_name: basic-auth-example
    networks:
      - traefiknet
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart: unless-stopped
    labels:
      # router
      - 'traefik.enable=true'
      - 'traefik.http.routers.basic-auth-example.rule=Host(`basic-auth-example.{{ host_name }}`)'
      # https
      - 'traefik.http.routers.basic-auth-example.tls=true'
      - 'traefik.http.routers.basic-auth-example.tls.certresolver=production'
      - 'traefik.http.routers.basic-auth-example.entrypoints=websecure'
      # basic auth
      - 'traefik.http.routers.basic-auth-example.middlewares=basic-auth-example-auth'
      - "traefik.http.middlewares.basic-auth-example-auth.basicauth.usersfile=/config/basic-auth/usersfile"

networks:
  traefiknet:
    external: true
