---
- name: Install passlib python lib for basic auth generation
  pip:
    name: passlib
    state: present

- name: Create traefik network
  docker_network:
    name: traefiknet

- name: Ensure /opt/traefik exists
  file:
    path: /opt/traefik
    state: directory

- name: Template docker-compose
  template:
    src: docker-compose.yml
    dest: /opt/traefik/docker-compose.yml

- name: Ensure /opt/traefik/etc/traefik exists
  file:
    path: /opt/traefik/etc/traefik
    state: directory

- name: Template /etc/traefik
  template:
    src: traefik.yml
    dest: /opt/traefik/etc/traefik/traefik.yml

- name: Ensure /opt/traefik/config/basic-auth exists
  file:
    path: /opt/traefik/config/basic-auth
    state: directory

- name: Remove password usersfile / clearing it
  file:
    path: /opt/traefik/config/basic-auth/usersfile
    state: absent

- name: Add users to the password usersfile
  community.general.htpasswd:
    path: /opt/traefik/config/basic-auth/usersfile
    name: "{{ item.user }}"
    password: "{{ item.password }}"
  with_items: "{{ traefik_basic_auth }}"
  loop_control:
    label: "{{ item.user }}"

- name: Tear down existing services
  docker_compose:
    project_src: /opt/traefik
    state: absent
    remove_orphans: yes

- name: Create and start services
  docker_compose:
    project_src: /opt/traefik