---
- name: Ensure /opt/basic-auth-example exists
  file:
    path: /opt/basic-auth-example
    state: directory

- name: Ensure /opt/basic-auth-example/config exists
  file:
    path: /opt/basic-auth-example/config
    state: directory

- name: Template docker-compose
  template:
    src: docker-compose.yml
    dest: /opt/basic-auth-example/docker-compose.yml

- name: Tear down existing services
  docker_compose:
    project_src: /opt/basic-auth-example
    state: absent
    remove_orphans: yes

- name: Create and start services
  docker_compose:
    project_src: /opt/basic-auth-example